/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUserResponseDtoRole } from './adminUserResponseDtoRole';

export interface AdminUserResponseDto {
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  name: string | null;
  role: AdminUserResponseDtoRole;
  createdAt: string;
  updatedAt: string;
}
