/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUpdateEducationOrganizationDtoGroupValidationMode =
  (typeof AdminUpdateEducationOrganizationDtoGroupValidationMode)[keyof typeof AdminUpdateEducationOrganizationDtoGroupValidationMode];

export const AdminUpdateEducationOrganizationDtoGroupValidationMode = {
  NONE: 'NONE',
  HINT: 'HINT',
  STRICT: 'STRICT',
} as const;
