/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * Что на самом деле лежит в записи анализа: статус READY одинаков у заглушки и у настоящего ИИ-анализа
 */
export type AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisResultKind =
  (typeof AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisResultKind)[keyof typeof AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisResultKind];

export const AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisResultKind = {
  AI: 'AI',
  ALGORITHM_AI_PENDING: 'ALGORITHM_AI_PENDING',
  ALGORITHM_ONLY: 'ALGORITHM_ONLY',
  STUB: 'STUB',
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  MISSING: 'MISSING',
} as const;
