/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicLinksListResponseDtoLinksItemEntryProfileMode } from './adminPublicLinksListResponseDtoLinksItemEntryProfileMode';
import type { AdminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode } from './adminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode';
import type { AdminPublicLinksListResponseDtoLinksItemPublicBranding } from './adminPublicLinksListResponseDtoLinksItemPublicBranding';
import type { AdminPublicLinksListResponseDtoLinksItemPublicTemplate } from './adminPublicLinksListResponseDtoLinksItemPublicTemplate';

export type AdminPublicLinksListResponseDtoLinksItem = {
  id: number;
  publishedVersionId: number;
  topicId: number;
  /** @nullable */
  educationOrganizationId: number | null;
  /** @nullable */
  educationOrganizationName: string | null;
  personalDataProcessingMode: AdminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode;
  /** @nullable */
  operatorFullNameSnapshot: string | null;
  /** @nullable */
  operatorShortNameSnapshot: string | null;
  /** @nullable */
  operatorPrivacyPolicyUrlSnapshot: string | null;
  /** @nullable */
  operatorConsentDocumentUrlSnapshot: string | null;
  entryProfileMode: AdminPublicLinksListResponseDtoLinksItemEntryProfileMode;
  publicTemplate: AdminPublicLinksListResponseDtoLinksItemPublicTemplate;
  /** @nullable */
  publicBranding: AdminPublicLinksListResponseDtoLinksItemPublicBranding;
  shortCode: string;
  shortUrl: string;
  isActive: boolean;
  /** @nullable */
  archivedAt: string | null;
  /** @nullable */
  startsAt: string | null;
  /** @nullable */
  endsAt: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  maxAttemptsPerStudent: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  timeLimitMinutes: number | null;
  allowResume: boolean;
  consentVersion: string;
  consentText: string;
  title: string;
  updatedAt: string;
  createdAt: string;
};
