/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AdminPublicAttemptDetailResponseDtoStudentEducationLevel =
  | (typeof AdminPublicAttemptDetailResponseDtoStudentEducationLevel)[keyof typeof AdminPublicAttemptDetailResponseDtoStudentEducationLevel]
  | null;

export const AdminPublicAttemptDetailResponseDtoStudentEducationLevel = {
  BASIC_GENERAL: 'BASIC_GENERAL',
  SECONDARY_GENERAL: 'SECONDARY_GENERAL',
  SECONDARY_SPECIAL: 'SECONDARY_SPECIAL',
  INCOMPLETE_HIGHER_FROM_YEAR_3: 'INCOMPLETE_HIGHER_FROM_YEAR_3',
  HIGHER: 'HIGHER',
} as const;
