/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode =
  (typeof AdminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode)[keyof typeof AdminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode];

export const AdminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode = {
  DEMOGRAPHIC: 'DEMOGRAPHIC',
  EDUCATION: 'EDUCATION',
  EDUCATION_DEMOGRAPHIC: 'EDUCATION_DEMOGRAPHIC',
} as const;
