/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoCoverage = {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  publicLinks: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsTotal: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsCompleted: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  analysisReady: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  analysisPending: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  analysisFailed: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  analysisMissing: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  v3Results: number;
};
