/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicAttemptDetailResponseDtoAnalysis } from './adminPublicAttemptDetailResponseDtoAnalysis';
import type { AdminPublicAttemptDetailResponseDtoAnswersItem } from './adminPublicAttemptDetailResponseDtoAnswersItem';
import type { AdminPublicAttemptDetailResponseDtoStatus } from './adminPublicAttemptDetailResponseDtoStatus';

export interface AdminPublicAttemptDetailResponseDto {
  attemptId: number;
  publicLinkId: number;
  shortCode: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptNumber: number;
  status: AdminPublicAttemptDetailResponseDtoStatus;
  studentName: string;
  studentLastInitial: string;
  studentMiddleInitial: string;
  educationOrganization: string;
  groupOrClass: string;
  consentAcceptedAt: string;
  consentVersion: string;
  startedAt: string;
  /** @nullable */
  finishedAt: string | null;
  /** @nullable */
  expiresAt: string | null;
  answers: AdminPublicAttemptDetailResponseDtoAnswersItem[];
  /** @nullable */
  analysis: AdminPublicAttemptDetailResponseDtoAnalysis;
}
