/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminCreatePublicLinkDtoPublicTemplate =
  (typeof AdminCreatePublicLinkDtoPublicTemplate)[keyof typeof AdminCreatePublicLinkDtoPublicTemplate];

export const AdminCreatePublicLinkDtoPublicTemplate = {
  STANDARD: 'STANDARD',
  POLUS: 'POLUS',
} as const;
