/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoScoreAveragesItem = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  label: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  average: number;
};
