/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminCreatePublicLinkDtoPersonalDataProcessingMode =
  (typeof AdminCreatePublicLinkDtoPersonalDataProcessingMode)[keyof typeof AdminCreatePublicLinkDtoPersonalDataProcessingMode];

export const AdminCreatePublicLinkDtoPersonalDataProcessingMode = {
  PUBLIC: 'PUBLIC',
  ON_BEHALF_OF_EDUCATION_ORGANIZATION: 'ON_BEHALF_OF_EDUCATION_ORGANIZATION',
} as const;
