/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminOpenRouterSettingsResponseDtoOpenRouterHealthStatus =
  (typeof AdminOpenRouterSettingsResponseDtoOpenRouterHealthStatus)[keyof typeof AdminOpenRouterSettingsResponseDtoOpenRouterHealthStatus];

export const AdminOpenRouterSettingsResponseDtoOpenRouterHealthStatus = {
  ok: 'ok',
  failed: 'failed',
  not_configured: 'not_configured',
} as const;
