/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPromptModelsResponseDtoModelsItem = {
  id: string;
  label: string;
  provider: string;
  isFree: boolean;
  /** @nullable */
  contextLength: number | null;
  /** @nullable */
  promptPrice: number | null;
  /** @nullable */
  completionPrice: number | null;
};
