/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUserCredentialsResponseDtoUser } from './adminUserCredentialsResponseDtoUser';

export interface AdminUserCredentialsResponseDto {
  user: AdminUserCredentialsResponseDtoUser;
  /** @nullable */
  generatedPassword: string | null;
}
