/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminCreatePublicLinkDtoPublicBrandingAccents } from './adminCreatePublicLinkDtoPublicBrandingAccents';
import type { AdminCreatePublicLinkDtoPublicBrandingBackground } from './adminCreatePublicLinkDtoPublicBrandingBackground';
import type { AdminCreatePublicLinkDtoPublicBrandingButtons } from './adminCreatePublicLinkDtoPublicBrandingButtons';
import type { AdminCreatePublicLinkDtoPublicBrandingHeader } from './adminCreatePublicLinkDtoPublicBrandingHeader';
import type { AdminCreatePublicLinkDtoPublicBrandingSurfaces } from './adminCreatePublicLinkDtoPublicBrandingSurfaces';
import type { AdminCreatePublicLinkDtoPublicBrandingVersion } from './adminCreatePublicLinkDtoPublicBrandingVersion';

/**
 * @nullable
 */
export type AdminCreatePublicLinkDtoPublicBranding = {
  version: AdminCreatePublicLinkDtoPublicBrandingVersion;
  background?: AdminCreatePublicLinkDtoPublicBrandingBackground;
  header?: AdminCreatePublicLinkDtoPublicBrandingHeader;
  buttons?: AdminCreatePublicLinkDtoPublicBrandingButtons;
  surfaces?: AdminCreatePublicLinkDtoPublicBrandingSurfaces;
  accents?: AdminCreatePublicLinkDtoPublicBrandingAccents;
} | null;
