/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetUsersStatus =
  (typeof AdminControllerGetUsersStatus)[keyof typeof AdminControllerGetUsersStatus];

export const AdminControllerGetUsersStatus = {
  ACTIVE: 'ACTIVE',
  DEACTIVATED: 'DEACTIVATED',
} as const;
