/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUpdatePublicLinkDtoPersonalDataProcessingMode =
  (typeof AdminUpdatePublicLinkDtoPersonalDataProcessingMode)[keyof typeof AdminUpdatePublicLinkDtoPersonalDataProcessingMode];

export const AdminUpdatePublicLinkDtoPersonalDataProcessingMode = {
  PUBLIC: 'PUBLIC',
  ON_BEHALF_OF_EDUCATION_ORGANIZATION: 'ON_BEHALF_OF_EDUCATION_ORGANIZATION',
} as const;
