/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicLinkDtoPublicBrandingAccents } from './adminPublicLinkDtoPublicBrandingAccents';
import type { AdminPublicLinkDtoPublicBrandingBackground } from './adminPublicLinkDtoPublicBrandingBackground';
import type { AdminPublicLinkDtoPublicBrandingButtons } from './adminPublicLinkDtoPublicBrandingButtons';
import type { AdminPublicLinkDtoPublicBrandingHeader } from './adminPublicLinkDtoPublicBrandingHeader';
import type { AdminPublicLinkDtoPublicBrandingSurfaces } from './adminPublicLinkDtoPublicBrandingSurfaces';
import type { AdminPublicLinkDtoPublicBrandingVersion } from './adminPublicLinkDtoPublicBrandingVersion';

/**
 * @nullable
 */
export type AdminPublicLinkDtoPublicBranding = {
  version: AdminPublicLinkDtoPublicBrandingVersion;
  background?: AdminPublicLinkDtoPublicBrandingBackground;
  header?: AdminPublicLinkDtoPublicBrandingHeader;
  buttons?: AdminPublicLinkDtoPublicBrandingButtons;
  surfaces?: AdminPublicLinkDtoPublicBrandingSurfaces;
  accents?: AdminPublicLinkDtoPublicBrandingAccents;
} | null;
