/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminOverviewResponseDtoCardsItem = {
  id: string;
  label: string;
  value: number;
  trend: string;
};
