/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AdminPublicAttemptDetailResponseDtoAnalysis = {
  providerMode: 'STUB' | 'LLM';
  status: 'PENDING' | 'READY' | 'FAILED';
  summary: unknown | null;
  /** @nullable */
  rawText: string | null;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  generatedAt: string | null;
} | null;
