/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminEducationOrganizationDtoGroupValidationMode =
  (typeof AdminEducationOrganizationDtoGroupValidationMode)[keyof typeof AdminEducationOrganizationDtoGroupValidationMode];

export const AdminEducationOrganizationDtoGroupValidationMode = {
  NONE: 'NONE',
  HINT: 'HINT',
  STRICT: 'STRICT',
} as const;
