/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageStatus =
  (typeof AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageStatus)[keyof typeof AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageStatus];

export const AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageStatus = {
  ready: 'ready',
  partial: 'partial',
  unavailable: 'unavailable',
} as const;
