/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetUsersRole =
  (typeof AdminControllerGetUsersRole)[keyof typeof AdminControllerGetUsersRole];

export const AdminControllerGetUsersRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
