/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUpdateEducationOrganizationDtoGroupValidationMode } from './adminUpdateEducationOrganizationDtoGroupValidationMode';

export interface AdminUpdateEducationOrganizationDto {
  /**
   * @minLength 2
   * @maxLength 300
   */
  name?: string;
  isActive?: boolean;
  groupValidationMode?: AdminUpdateEducationOrganizationDtoGroupValidationMode;
  /**
   * @minLength 1
   * @maxLength 300
   * @nullable
   */
  groupValidationPattern?: string | null;
  /**
   * @minLength 1
   * @maxLength 120
   * @nullable
   */
  groupValidationExample?: string | null;
  /**
   * @minLength 1
   * @maxLength 300
   * @nullable
   */
  groupValidationHint?: string | null;
}
