/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUserResponseDtoRole =
  (typeof AdminUserResponseDtoRole)[keyof typeof AdminUserResponseDtoRole];

export const AdminUserResponseDtoRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
