/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminEducationOrganizationsListResponseDtoOrganizationsItemGroupValidationMode =
  (typeof AdminEducationOrganizationsListResponseDtoOrganizationsItemGroupValidationMode)[keyof typeof AdminEducationOrganizationsListResponseDtoOrganizationsItemGroupValidationMode];

export const AdminEducationOrganizationsListResponseDtoOrganizationsItemGroupValidationMode = {
  NONE: 'NONE',
  HINT: 'HINT',
  STRICT: 'STRICT',
} as const;
