/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinkDtoPublicTemplate =
  (typeof AdminPublicLinkDtoPublicTemplate)[keyof typeof AdminPublicLinkDtoPublicTemplate];

export const AdminPublicLinkDtoPublicTemplate = {
  STANDARD: 'STANDARD',
  POLUS: 'POLUS',
} as const;
