/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinksListResponseDtoLinksItemPublicBrandingVersion =
  (typeof AdminPublicLinksListResponseDtoLinksItemPublicBrandingVersion)[keyof typeof AdminPublicLinksListResponseDtoLinksItemPublicBrandingVersion];

export const AdminPublicLinksListResponseDtoLinksItemPublicBrandingVersion = {
  NUMBER_1: 1,
} as const;
