/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize =
  (typeof AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize)[keyof typeof AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize];

export const AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize = {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
