/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicAttemptsListResponseDtoAttemptsItem } from './adminPublicAttemptsListResponseDtoAttemptsItem';

export interface AdminPublicAttemptsListResponseDto {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  limit: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  total: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  totalPages: number;
  attempts: AdminPublicAttemptsListResponseDtoAttemptsItem[];
}
