/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminCreatePublicLinkDtoPublicBrandingVersion =
  (typeof AdminCreatePublicLinkDtoPublicBrandingVersion)[keyof typeof AdminCreatePublicLinkDtoPublicBrandingVersion];

export const AdminCreatePublicLinkDtoPublicBrandingVersion = {
  NUMBER_1: 1,
} as const;
