/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface AdminCreatePublicLinkDto {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  publishedVersionId: number;
  /**
   * @minLength 4
   * @maxLength 32
   */
  shortCode?: string;
  isActive?: boolean;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  startsAt?: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  endsAt?: string | null;
  /**
   * @minimum 1
   * @maximum 20
   */
  maxAttemptsPerStudent?: number;
  /**
   * @minimum 1
   * @maximum 600
   * @nullable
   */
  timeLimitMinutes?: number | null;
  allowResume?: boolean;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  educationOrganizationId?: number | null;
  /**
   * @minLength 1
   * @maxLength 64
   */
  consentVersion: string;
  /**
   * @minLength 1
   * @maxLength 16000
   */
  consentText: string;
}
