/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicAttemptDetailResponseDtoAnalysisResultKind =
  (typeof AdminPublicAttemptDetailResponseDtoAnalysisResultKind)[keyof typeof AdminPublicAttemptDetailResponseDtoAnalysisResultKind];

export const AdminPublicAttemptDetailResponseDtoAnalysisResultKind = {
  AI: 'AI',
  ALGORITHM_AI_PENDING: 'ALGORITHM_AI_PENDING',
  ALGORITHM_ONLY: 'ALGORITHM_ONLY',
  STUB: 'STUB',
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  MISSING: 'MISSING',
} as const;
