/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminTestAnalyticsSummaryDtoDemographicsAgeRangeItem } from './adminTestAnalyticsSummaryDtoDemographicsAgeRangeItem';
import type { AdminTestAnalyticsSummaryDtoDemographicsEducationLevelItem } from './adminTestAnalyticsSummaryDtoDemographicsEducationLevelItem';
import type { AdminTestAnalyticsSummaryDtoDemographicsGenderItem } from './adminTestAnalyticsSummaryDtoDemographicsGenderItem';
import type { AdminTestAnalyticsSummaryDtoDemographicsResidenceItem } from './adminTestAnalyticsSummaryDtoDemographicsResidenceItem';

export type AdminTestAnalyticsSummaryDtoDemographics = {
  gender: AdminTestAnalyticsSummaryDtoDemographicsGenderItem[];
  ageRange: AdminTestAnalyticsSummaryDtoDemographicsAgeRangeItem[];
  residence: AdminTestAnalyticsSummaryDtoDemographicsResidenceItem[];
  educationLevel: AdminTestAnalyticsSummaryDtoDemographicsEducationLevelItem[];
};
