/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminCreateEducationOrganizationDtoGroupValidationMode } from './adminCreateEducationOrganizationDtoGroupValidationMode';

export interface AdminCreateEducationOrganizationDto {
  /**
   * @minLength 2
   * @maxLength 300
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 500
   * @nullable
   */
  fullName?: string | null;
  /**
   * @minLength 1
   * @maxLength 300
   * @nullable
   */
  shortName?: string | null;
  /**
   * @minLength 1
   * @maxLength 20
   * @nullable
   */
  inn?: string | null;
  /**
   * @minLength 1
   * @maxLength 20
   * @nullable
   */
  ogrn?: string | null;
  /**
   * @minLength 1
   * @maxLength 500
   * @nullable
   */
  legalAddress?: string | null;
  /**
   * @minLength 1
   * @maxLength 320
   * @nullable
   */
  email?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   * @nullable
   */
  phone?: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  privacyPolicyUrl?: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  consentDocumentUrl?: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  logoUrl?: string | null;
  groupValidationMode?: AdminCreateEducationOrganizationDtoGroupValidationMode;
  /**
   * @minLength 1
   * @maxLength 300
   * @nullable
   */
  groupValidationPattern?: string | null;
  /**
   * @minLength 1
   * @maxLength 120
   * @nullable
   */
  groupValidationExample?: string | null;
  /**
   * @minLength 1
   * @maxLength 300
   * @nullable
   */
  groupValidationHint?: string | null;
}
