/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminControllerGetUsersRole } from './adminControllerGetUsersRole';
import type { AdminControllerGetUsersSortBy } from './adminControllerGetUsersSortBy';
import type { AdminControllerGetUsersSortOrder } from './adminControllerGetUsersSortOrder';

export type AdminControllerGetUsersParams = {
  /**
   * @minLength 1
   * @maxLength 100
   */
  search?: string;
  role?: AdminControllerGetUsersRole;
  sortBy?: AdminControllerGetUsersSortBy;
  sortOrder?: AdminControllerGetUsersSortOrder;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
};
