/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminAiProviderSettingsResponseDtoAiProviderHealth } from './adminAiProviderSettingsResponseDtoAiProviderHealth';
import type { AdminAiProviderSettingsResponseDtoAiProviderProvider } from './adminAiProviderSettingsResponseDtoAiProviderProvider';
import type { AdminAiProviderSettingsResponseDtoAiProviderSource } from './adminAiProviderSettingsResponseDtoAiProviderSource';

export type AdminAiProviderSettingsResponseDtoAiProvider = {
  provider: AdminAiProviderSettingsResponseDtoAiProviderProvider;
  label: string;
  /** @nullable */
  baseUrl: string | null;
  /** @nullable */
  defaultModel: string | null;
  isConfigured: boolean;
  /** @nullable */
  maskedValue: string | null;
  source: AdminAiProviderSettingsResponseDtoAiProviderSource;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  updatedAt: string | null;
  health: AdminAiProviderSettingsResponseDtoAiProviderHealth;
};
