/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetUsersSortOrder =
  (typeof AdminControllerGetUsersSortOrder)[keyof typeof AdminControllerGetUsersSortOrder];

export const AdminControllerGetUsersSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
