/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUpdatePublicLinkDtoPublicBrandingBackgroundMode } from './adminUpdatePublicLinkDtoPublicBrandingBackgroundMode';

export type AdminUpdatePublicLinkDtoPublicBrandingBackground = {
  mode?: AdminUpdatePublicLinkDtoPublicBrandingBackgroundMode;
  /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
  color?: string;
  /** @maxLength 2048 */
  imageUrl?: string;
  /**
   * @minimum 0
   * @maximum 0.85
   */
  overlay?: number;
};
