/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoFlagsItem = {
  /** @minLength 1 */
  flag: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  count: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  share: number;
};
