/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicLinkDtoPublicBrandingHeaderLogosItemSize } from './adminPublicLinkDtoPublicBrandingHeaderLogosItemSize';

export type AdminPublicLinkDtoPublicBrandingHeaderLogosItem = {
  /** @maxLength 2048 */
  url: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  alt: string;
  size?: AdminPublicLinkDtoPublicBrandingHeaderLogosItemSize;
};
