/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetUsersSortBy =
  (typeof AdminControllerGetUsersSortBy)[keyof typeof AdminControllerGetUsersSortBy];

export const AdminControllerGetUsersSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
