/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUsersResponseDtoUsersItemRole =
  (typeof AdminUsersResponseDtoUsersItemRole)[keyof typeof AdminUsersResponseDtoUsersItemRole];

export const AdminUsersResponseDtoUsersItemRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
