/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode =
  (typeof AdminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode)[keyof typeof AdminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode];

export const AdminPublicLinksListResponseDtoLinksItemPersonalDataProcessingMode = {
  PUBLIC: 'PUBLIC',
  ON_BEHALF_OF_EDUCATION_ORGANIZATION: 'ON_BEHALF_OF_EDUCATION_ORGANIZATION',
} as const;
