/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoFiltersScope =
  (typeof AdminTestAnalyticsSummaryDtoFiltersScope)[keyof typeof AdminTestAnalyticsSummaryDtoFiltersScope];

export const AdminTestAnalyticsSummaryDtoFiltersScope = {
  TOPIC: 'TOPIC',
  PUBLIC_LINK: 'PUBLIC_LINK',
} as const;
