/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminOverviewResponseDtoCardsItem } from './adminOverviewResponseDtoCardsItem';
import type { AdminOverviewResponseDtoShortcutsItem } from './adminOverviewResponseDtoShortcutsItem';

export interface AdminOverviewResponseDto {
  title: string;
  subtitle: string;
  cards: AdminOverviewResponseDtoCardsItem[];
  shortcuts: AdminOverviewResponseDtoShortcutsItem[];
}
