/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * Статус асинхронного LLM-обогащения для двухфазного анализа
 * @nullable
 */
export type AdminPublicAttemptsListResponseDtoAttemptsItemLlmStatus =
  | (typeof AdminPublicAttemptsListResponseDtoAttemptsItemLlmStatus)[keyof typeof AdminPublicAttemptsListResponseDtoAttemptsItemLlmStatus]
  | null;

export const AdminPublicAttemptsListResponseDtoAttemptsItemLlmStatus = {
  not_requested: 'not_requested',
  pending: 'pending',
  ready: 'ready',
  failed: 'failed',
} as const;
