/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoTopic = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  topicId: number;
  /** @minLength 1 */
  slug: string;
  /** @minLength 1 */
  title: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  questionCount: number;
  generatedAt: string;
};
