/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminAiProviderSettingsResponseDtoAiProviderProvider =
  (typeof AdminAiProviderSettingsResponseDtoAiProviderProvider)[keyof typeof AdminAiProviderSettingsResponseDtoAiProviderProvider];

export const AdminAiProviderSettingsResponseDtoAiProviderProvider = {
  polza: 'polza',
  openrouter: 'openrouter',
  'openai-compatible': 'openai-compatible',
} as const;
