/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoDemographicsAgeRangeItem = {
  /** @minLength 1 */
  label: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  count: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  share: number;
};
