/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus =
  | (typeof AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus)[keyof typeof AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus]
  | null;

export const AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus = {
  PENDING: 'PENDING',
  READY: 'READY',
  FAILED: 'FAILED',
} as const;
