/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoTopicScoringKind =
  (typeof AdminTestAnalyticsSummaryDtoTopicScoringKind)[keyof typeof AdminTestAnalyticsSummaryDtoTopicScoringKind];

export const AdminTestAnalyticsSummaryDtoTopicScoringKind = {
  DEFAULT: 'DEFAULT',
  PROF_ORIENTATION_V3_PLUS: 'PROF_ORIENTATION_V3_PLUS',
} as const;
