/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUpdatePublicLinkDtoEntryProfileMode =
  (typeof AdminUpdatePublicLinkDtoEntryProfileMode)[keyof typeof AdminUpdatePublicLinkDtoEntryProfileMode];

export const AdminUpdatePublicLinkDtoEntryProfileMode = {
  DEMOGRAPHIC: 'DEMOGRAPHIC',
  EDUCATION: 'EDUCATION',
} as const;
