/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminEducationOrganizationDtoGroupValidationMode } from './adminEducationOrganizationDtoGroupValidationMode';

export interface AdminEducationOrganizationDto {
  id: number;
  name: string;
  /** @nullable */
  fullName: string | null;
  /** @nullable */
  shortName: string | null;
  /** @nullable */
  inn: string | null;
  /** @nullable */
  ogrn: string | null;
  /** @nullable */
  legalAddress: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  privacyPolicyUrl: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  consentDocumentUrl: string | null;
  /**
   * @maxLength 2048
   * @nullable
   */
  logoUrl: string | null;
  personalDataReady: boolean;
  isActive: boolean;
  groupValidationMode: AdminEducationOrganizationDtoGroupValidationMode;
  /** @nullable */
  groupValidationPattern: string | null;
  /** @nullable */
  groupValidationExample: string | null;
  /** @nullable */
  groupValidationHint: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  linksCount: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  activeLinksCount: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsCount: number;
  createdAt: string;
  updatedAt: string;
}
