/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminOpenRouterSettingsResponseDtoOpenRouterSource =
  (typeof AdminOpenRouterSettingsResponseDtoOpenRouterSource)[keyof typeof AdminOpenRouterSettingsResponseDtoOpenRouterSource];

export const AdminOpenRouterSettingsResponseDtoOpenRouterSource = {
  DATABASE: 'DATABASE',
  ENV: 'ENV',
  NONE: 'NONE',
} as const;
