/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisStatus } from './adminPublicAttemptsListResponseDtoAttemptsItemAnalysisStatus';
import type { AdminPublicAttemptsListResponseDtoAttemptsItemStatus } from './adminPublicAttemptsListResponseDtoAttemptsItemStatus';

export type AdminPublicAttemptsListResponseDtoAttemptsItem = {
  attemptId: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptNumber: number;
  status: AdminPublicAttemptsListResponseDtoAttemptsItemStatus;
  studentName: string;
  studentLastInitial: string;
  studentMiddleInitial: string;
  educationOrganization: string;
  groupOrClass: string;
  startedAt: string;
  /** @nullable */
  finishedAt: string | null;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  analysisStatus: AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisStatus;
};
