/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicAttemptDetailResponseDtoStatus =
  (typeof AdminPublicAttemptDetailResponseDtoStatus)[keyof typeof AdminPublicAttemptDetailResponseDtoStatus];

export const AdminPublicAttemptDetailResponseDtoStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  ABANDONED: 'ABANDONED',
} as const;
