/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoGroupsItem = {
  /** @nullable */
  educationOrganization: string | null;
  /** @nullable */
  groupOrClass: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsTotal: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsCompleted: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  share: number;
};
