/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinksListResponseDtoLinksItemPublicTemplate =
  (typeof AdminPublicLinksListResponseDtoLinksItemPublicTemplate)[keyof typeof AdminPublicLinksListResponseDtoLinksItemPublicTemplate];

export const AdminPublicLinksListResponseDtoLinksItemPublicTemplate = {
  STANDARD: 'STANDARD',
  POLUS: 'POLUS',
} as const;
