/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicAttemptDetailResponseDtoAnalysis } from './adminPublicAttemptDetailResponseDtoAnalysis';
import type { AdminPublicAttemptDetailResponseDtoAnswersItem } from './adminPublicAttemptDetailResponseDtoAnswersItem';
import type { AdminPublicAttemptDetailResponseDtoEntryProfileMode } from './adminPublicAttemptDetailResponseDtoEntryProfileMode';
import type { AdminPublicAttemptDetailResponseDtoStatus } from './adminPublicAttemptDetailResponseDtoStatus';
import type { AdminPublicAttemptDetailResponseDtoStudentEducationLevel } from './adminPublicAttemptDetailResponseDtoStudentEducationLevel';
import type { AdminPublicAttemptDetailResponseDtoStudentGender } from './adminPublicAttemptDetailResponseDtoStudentGender';

export interface AdminPublicAttemptDetailResponseDto {
  attemptId: number;
  publicLinkId: number;
  shortCode: string;
  /** @nullable */
  professionAtlasUrl: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptNumber: number;
  status: AdminPublicAttemptDetailResponseDtoStatus;
  entryProfileMode: AdminPublicAttemptDetailResponseDtoEntryProfileMode;
  /** @nullable */
  studentName: string | null;
  /** @nullable */
  studentLastInitial: string | null;
  /** @nullable */
  studentMiddleInitial: string | null;
  /** @nullable */
  educationOrganization: string | null;
  /** @nullable */
  groupOrClass: string | null;
  /** @nullable */
  studentGender: AdminPublicAttemptDetailResponseDtoStudentGender;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  studentAge: number | null;
  /** @nullable */
  studentResidence: string | null;
  /** @nullable */
  studentEducationLevel: AdminPublicAttemptDetailResponseDtoStudentEducationLevel;
  consentAcceptedAt: string;
  consentVersion: string;
  startedAt: string;
  /** @nullable */
  finishedAt: string | null;
  /** @nullable */
  expiresAt: string | null;
  answers: AdminPublicAttemptDetailResponseDtoAnswersItem[];
  /** @nullable */
  analysis: AdminPublicAttemptDetailResponseDtoAnalysis;
}
