/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUpdatePublicLinkDtoPublicBrandingAccents } from './adminUpdatePublicLinkDtoPublicBrandingAccents';
import type { AdminUpdatePublicLinkDtoPublicBrandingBackground } from './adminUpdatePublicLinkDtoPublicBrandingBackground';
import type { AdminUpdatePublicLinkDtoPublicBrandingButtons } from './adminUpdatePublicLinkDtoPublicBrandingButtons';
import type { AdminUpdatePublicLinkDtoPublicBrandingHeader } from './adminUpdatePublicLinkDtoPublicBrandingHeader';
import type { AdminUpdatePublicLinkDtoPublicBrandingSurfaces } from './adminUpdatePublicLinkDtoPublicBrandingSurfaces';
import type { AdminUpdatePublicLinkDtoPublicBrandingVersion } from './adminUpdatePublicLinkDtoPublicBrandingVersion';

/**
 * @nullable
 */
export type AdminUpdatePublicLinkDtoPublicBranding = {
  version: AdminUpdatePublicLinkDtoPublicBrandingVersion;
  background?: AdminUpdatePublicLinkDtoPublicBrandingBackground;
  header?: AdminUpdatePublicLinkDtoPublicBrandingHeader;
  buttons?: AdminUpdatePublicLinkDtoPublicBrandingButtons;
  surfaces?: AdminUpdatePublicLinkDtoPublicBrandingSurfaces;
  accents?: AdminUpdatePublicLinkDtoPublicBrandingAccents;
} | null;
