/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUsersResponseDtoUsersItemRole } from './adminUsersResponseDtoUsersItemRole';

export type AdminUsersResponseDtoUsersItem = {
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  name: string | null;
  role: AdminUsersResponseDtoUsersItemRole;
  createdAt: string;
  updatedAt: string;
};
