/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicLinksListResponseDtoLinksItemEntryProfileMode } from './adminPublicLinksListResponseDtoLinksItemEntryProfileMode';

export type AdminPublicLinksListResponseDtoLinksItem = {
  id: number;
  publishedVersionId: number;
  topicId: number;
  /** @nullable */
  educationOrganizationId: number | null;
  /** @nullable */
  educationOrganizationName: string | null;
  entryProfileMode: AdminPublicLinksListResponseDtoLinksItemEntryProfileMode;
  shortCode: string;
  shortUrl: string;
  isActive: boolean;
  /** @nullable */
  archivedAt: string | null;
  /** @nullable */
  startsAt: string | null;
  /** @nullable */
  endsAt: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  maxAttemptsPerStudent: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  timeLimitMinutes: number | null;
  allowResume: boolean;
  consentVersion: string;
  consentText: string;
  title: string;
  updatedAt: string;
  createdAt: string;
};
