/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUpdatePublicLinkDtoPublicBrandingBackgroundMode =
  (typeof AdminUpdatePublicLinkDtoPublicBrandingBackgroundMode)[keyof typeof AdminUpdatePublicLinkDtoPublicBrandingBackgroundMode];

export const AdminUpdatePublicLinkDtoPublicBrandingBackgroundMode = {
  default: 'default',
  solid: 'solid',
  image: 'image',
} as const;
