/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUserCredentialsResponseDtoUserRole } from './adminUserCredentialsResponseDtoUserRole';

export type AdminUserCredentialsResponseDtoUser = {
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  name: string | null;
  role: AdminUserCredentialsResponseDtoUserRole;
  /** @nullable */
  deactivatedAt: string | null;
  /** @nullable */
  lastLoginAt: string | null;
  createdAt: string;
  updatedAt: string;
};
