/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinkDtoPublicBrandingHeaderLogosItemSize =
  (typeof AdminPublicLinkDtoPublicBrandingHeaderLogosItemSize)[keyof typeof AdminPublicLinkDtoPublicBrandingHeaderLogosItemSize];

export const AdminPublicLinkDtoPublicBrandingHeaderLogosItemSize = {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
