/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminUpdatePublicLinkDtoPublicBrandingHeaderLogosItemSize } from './adminUpdatePublicLinkDtoPublicBrandingHeaderLogosItemSize';

export type AdminUpdatePublicLinkDtoPublicBrandingHeaderLogosItem = {
  /** @maxLength 2048 */
  url: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  alt: string;
  size?: AdminUpdatePublicLinkDtoPublicBrandingHeaderLogosItemSize;
};
