/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicAttemptDetailResponseDtoAnalysisStatus =
  (typeof AdminPublicAttemptDetailResponseDtoAnalysisStatus)[keyof typeof AdminPublicAttemptDetailResponseDtoAnalysisStatus];

export const AdminPublicAttemptDetailResponseDtoAnalysisStatus = {
  PENDING: 'PENDING',
  READY: 'READY',
  FAILED: 'FAILED',
} as const;
