/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize';

export type AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItem = {
  /** @maxLength 2048 */
  url: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  alt: string;
  size?: AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeaderLogosItemSize;
};
