/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminAiProviderSettingsResponseDtoAiProviderHealthStatus =
  (typeof AdminAiProviderSettingsResponseDtoAiProviderHealthStatus)[keyof typeof AdminAiProviderSettingsResponseDtoAiProviderHealthStatus];

export const AdminAiProviderSettingsResponseDtoAiProviderHealthStatus = {
  ok: 'ok',
  failed: 'failed',
  not_configured: 'not_configured',
} as const;
