/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinkDtoEntryProfileMode =
  (typeof AdminPublicLinkDtoEntryProfileMode)[keyof typeof AdminPublicLinkDtoEntryProfileMode];

export const AdminPublicLinkDtoEntryProfileMode = {
  DEMOGRAPHIC: 'DEMOGRAPHIC',
  EDUCATION: 'EDUCATION',
  EDUCATION_DEMOGRAPHIC: 'EDUCATION_DEMOGRAPHIC',
} as const;
