/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicAttemptDetailResponseDtoAnalysisProviderMode } from './adminPublicAttemptDetailResponseDtoAnalysisProviderMode';
import type { AdminPublicAttemptDetailResponseDtoAnalysisStatus } from './adminPublicAttemptDetailResponseDtoAnalysisStatus';

/**
 * @nullable
 */
export type AdminPublicAttemptDetailResponseDtoAnalysis = {
  providerMode: AdminPublicAttemptDetailResponseDtoAnalysisProviderMode;
  status: AdminPublicAttemptDetailResponseDtoAnalysisStatus;
  summary: unknown | null;
  /** @nullable */
  rawText: string | null;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  generatedAt: string | null;
} | null;
