/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminCreatePublicLinkDtoPublicBrandingHeaderLogosItem } from './adminCreatePublicLinkDtoPublicBrandingHeaderLogosItem';

export type AdminCreatePublicLinkDtoPublicBrandingHeader = {
  /** @maxItems 2 */
  logos?: AdminCreatePublicLinkDtoPublicBrandingHeaderLogosItem[];
};
