/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingAccents } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingAccents';
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingBackground } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingBackground';
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingButtons } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingButtons';
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeader } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingHeader';
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingSurfaces } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingSurfaces';
import type { AdminPublicLinksListResponseDtoLinksItemPublicBrandingVersion } from './adminPublicLinksListResponseDtoLinksItemPublicBrandingVersion';

/**
 * @nullable
 */
export type AdminPublicLinksListResponseDtoLinksItemPublicBranding = {
  version: AdminPublicLinksListResponseDtoLinksItemPublicBrandingVersion;
  background?: AdminPublicLinksListResponseDtoLinksItemPublicBrandingBackground;
  header?: AdminPublicLinksListResponseDtoLinksItemPublicBrandingHeader;
  buttons?: AdminPublicLinksListResponseDtoLinksItemPublicBrandingButtons;
  surfaces?: AdminPublicLinksListResponseDtoLinksItemPublicBrandingSurfaces;
  accents?: AdminPublicLinksListResponseDtoLinksItemPublicBrandingAccents;
} | null;
