/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoAttemptsItemStatus =
  (typeof AdminTestAnalyticsSummaryDtoAttemptsItemStatus)[keyof typeof AdminTestAnalyticsSummaryDtoAttemptsItemStatus];

export const AdminTestAnalyticsSummaryDtoAttemptsItemStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  ABANDONED: 'ABANDONED',
} as const;
