/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisStatus } from './adminPublicAttemptsListResponseDtoAttemptsItemAnalysisStatus';
import type { AdminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode } from './adminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode';
import type { AdminPublicAttemptsListResponseDtoAttemptsItemStatus } from './adminPublicAttemptsListResponseDtoAttemptsItemStatus';
import type { AdminPublicAttemptsListResponseDtoAttemptsItemStudentEducationLevel } from './adminPublicAttemptsListResponseDtoAttemptsItemStudentEducationLevel';
import type { AdminPublicAttemptsListResponseDtoAttemptsItemStudentGender } from './adminPublicAttemptsListResponseDtoAttemptsItemStudentGender';

export type AdminPublicAttemptsListResponseDtoAttemptsItem = {
  attemptId: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptNumber: number;
  status: AdminPublicAttemptsListResponseDtoAttemptsItemStatus;
  entryProfileMode: AdminPublicAttemptsListResponseDtoAttemptsItemEntryProfileMode;
  /** @nullable */
  studentName: string | null;
  /** @nullable */
  studentLastInitial: string | null;
  /** @nullable */
  studentMiddleInitial: string | null;
  /** @nullable */
  educationOrganization: string | null;
  /** @nullable */
  groupOrClass: string | null;
  /** @nullable */
  studentGender: AdminPublicAttemptsListResponseDtoAttemptsItemStudentGender;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  studentAge: number | null;
  /** @nullable */
  studentResidence: string | null;
  /** @nullable */
  studentEducationLevel: AdminPublicAttemptsListResponseDtoAttemptsItemStudentEducationLevel;
  startedAt: string;
  /** @nullable */
  finishedAt: string | null;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  analysisStatus: AdminPublicAttemptsListResponseDtoAttemptsItemAnalysisStatus;
};
