/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus } from './adminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus';
import type { AdminTestAnalyticsSummaryDtoAttemptsItemLlmStatus } from './adminTestAnalyticsSummaryDtoAttemptsItemLlmStatus';
import type { AdminTestAnalyticsSummaryDtoAttemptsItemStatus } from './adminTestAnalyticsSummaryDtoAttemptsItemStatus';

export type AdminTestAnalyticsSummaryDtoAttemptsItem = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptId: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  publicLinkId: number;
  /** @minLength 1 */
  shortCode: string;
  startedAt: string;
  /** @nullable */
  finishedAt: string | null;
  status: AdminTestAnalyticsSummaryDtoAttemptsItemStatus;
  /**
   * Статус алгоритмической записи анализа (не является признаком завершения LLM-обогащения)
   * @nullable
   */
  analysisStatus: AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus;
  /**
   * Статус асинхронного LLM-обогащения для двухфазного анализа
   * @nullable
   */
  llmStatus: AdminTestAnalyticsSummaryDtoAttemptsItemLlmStatus;
};
