/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminCreateEducationOrganizationDtoGroupValidationMode = typeof AdminCreateEducationOrganizationDtoGroupValidationMode[keyof typeof AdminCreateEducationOrganizationDtoGroupValidationMode];


export const AdminCreateEducationOrganizationDtoGroupValidationMode = {
  NONE: 'NONE',
  HINT: 'HINT',
  STRICT: 'STRICT',
} as const;
