/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminPrivacyPolicySettingsResponseDtoPrivacyPolicy } from './adminPrivacyPolicySettingsResponseDtoPrivacyPolicy';

export interface AdminPrivacyPolicySettingsResponseDto {
  privacyPolicy: AdminPrivacyPolicySettingsResponseDtoPrivacyPolicy;
}
