/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicAttemptDetailResponseDtoAnswersItem = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  questionId: number;
  questionType: string;
  questionTitle: string;
  answerPayload: unknown;
  updatedAt: string;
};
