/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicLinkDtoPublicBrandingBackgroundMode =
  (typeof AdminPublicLinkDtoPublicBrandingBackgroundMode)[keyof typeof AdminPublicLinkDtoPublicBrandingBackgroundMode];

export const AdminPublicLinkDtoPublicBrandingBackgroundMode = {
  default: 'default',
  solid: 'solid',
  image: 'image',
} as const;
