/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUpdatePublicLinkDtoPublicBrandingVersion =
  (typeof AdminUpdatePublicLinkDtoPublicBrandingVersion)[keyof typeof AdminUpdatePublicLinkDtoPublicBrandingVersion];

export const AdminUpdatePublicLinkDtoPublicBrandingVersion = {
  NUMBER_1: 1,
} as const;
