/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminTestAnalyticsSummaryDtoAttemptsItem } from './adminTestAnalyticsSummaryDtoAttemptsItem';
import type { AdminTestAnalyticsSummaryDtoConfidence } from './adminTestAnalyticsSummaryDtoConfidence';
import type { AdminTestAnalyticsSummaryDtoCoverage } from './adminTestAnalyticsSummaryDtoCoverage';
import type { AdminTestAnalyticsSummaryDtoDemographics } from './adminTestAnalyticsSummaryDtoDemographics';
import type { AdminTestAnalyticsSummaryDtoDirectionPairsItem } from './adminTestAnalyticsSummaryDtoDirectionPairsItem';
import type { AdminTestAnalyticsSummaryDtoDirectionsItem } from './adminTestAnalyticsSummaryDtoDirectionsItem';
import type { AdminTestAnalyticsSummaryDtoFilters } from './adminTestAnalyticsSummaryDtoFilters';
import type { AdminTestAnalyticsSummaryDtoFlagsItem } from './adminTestAnalyticsSummaryDtoFlagsItem';
import type { AdminTestAnalyticsSummaryDtoGroupsItem } from './adminTestAnalyticsSummaryDtoGroupsItem';
import type { AdminTestAnalyticsSummaryDtoProfilesItem } from './adminTestAnalyticsSummaryDtoProfilesItem';
import type { AdminTestAnalyticsSummaryDtoPublicLinksItem } from './adminTestAnalyticsSummaryDtoPublicLinksItem';
import type { AdminTestAnalyticsSummaryDtoScoreAveragesItem } from './adminTestAnalyticsSummaryDtoScoreAveragesItem';
import type { AdminTestAnalyticsSummaryDtoTopic } from './adminTestAnalyticsSummaryDtoTopic';

export interface AdminTestAnalyticsSummaryDto {
  topic: AdminTestAnalyticsSummaryDtoTopic;
  filters: AdminTestAnalyticsSummaryDtoFilters;
  coverage: AdminTestAnalyticsSummaryDtoCoverage;
  directions: AdminTestAnalyticsSummaryDtoDirectionsItem[];
  directionPairs: AdminTestAnalyticsSummaryDtoDirectionPairsItem[];
  scoreAverages: AdminTestAnalyticsSummaryDtoScoreAveragesItem[];
  profiles: AdminTestAnalyticsSummaryDtoProfilesItem[];
  confidence: AdminTestAnalyticsSummaryDtoConfidence;
  flags: AdminTestAnalyticsSummaryDtoFlagsItem[];
  publicLinks: AdminTestAnalyticsSummaryDtoPublicLinksItem[];
  groups: AdminTestAnalyticsSummaryDtoGroupsItem[];
  demographics: AdminTestAnalyticsSummaryDtoDemographics;
  attempts: AdminTestAnalyticsSummaryDtoAttemptsItem[];
}
