/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminTestAnalyticsSummaryDtoFiltersLinkStatus } from './adminTestAnalyticsSummaryDtoFiltersLinkStatus';
import type { AdminTestAnalyticsSummaryDtoFiltersScope } from './adminTestAnalyticsSummaryDtoFiltersScope';

export type AdminTestAnalyticsSummaryDtoFilters = {
  scope: AdminTestAnalyticsSummaryDtoFiltersScope;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  publicLinkId: number | null;
  linkStatus: AdminTestAnalyticsSummaryDtoFiltersLinkStatus;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  dateFrom: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  dateTo: string | null;
};
