/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItemMatchesItem } from './adminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItemMatchesItem';
import type { AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItemStatus } from './adminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItemStatus';

export type AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItem = {
  title: string;
  status: AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItemStatus;
  matches: AdminProfessionAtlasSettingsResponseDtoProfessionAtlasCoverageItemsItemMatchesItem[];
};
