/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminTestAnalyticsSummaryDtoConfidenceConsistencyIndex } from './adminTestAnalyticsSummaryDtoConfidenceConsistencyIndex';
import type { AdminTestAnalyticsSummaryDtoConfidenceGap } from './adminTestAnalyticsSummaryDtoConfidenceGap';
import type { AdminTestAnalyticsSummaryDtoConfidenceLevelsItem } from './adminTestAnalyticsSummaryDtoConfidenceLevelsItem';
import type { AdminTestAnalyticsSummaryDtoConfidenceReadinessTop } from './adminTestAnalyticsSummaryDtoConfidenceReadinessTop';

export type AdminTestAnalyticsSummaryDtoConfidence = {
  levels: AdminTestAnalyticsSummaryDtoConfidenceLevelsItem[];
  gap: AdminTestAnalyticsSummaryDtoConfidenceGap;
  consistencyIndex: AdminTestAnalyticsSummaryDtoConfidenceConsistencyIndex;
  readinessTop: AdminTestAnalyticsSummaryDtoConfidenceReadinessTop;
};
