/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus } from './adminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus';
import type { AdminTestAnalyticsSummaryDtoAttemptsItemStatus } from './adminTestAnalyticsSummaryDtoAttemptsItemStatus';

export type AdminTestAnalyticsSummaryDtoAttemptsItem = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptId: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  publicLinkId: number;
  /** @minLength 1 */
  shortCode: string;
  startedAt: string;
  /** @nullable */
  finishedAt: string | null;
  status: AdminTestAnalyticsSummaryDtoAttemptsItemStatus;
  /** @nullable */
  analysisStatus: AdminTestAnalyticsSummaryDtoAttemptsItemAnalysisStatus;
};
