/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoPublicLinksItem = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  publicLinkId: number;
  /** @minLength 1 */
  shortCode: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  archivedAt: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsTotal: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptsCompleted: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  analysisReady: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  share: number;
};
