/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminTestAnalyticsSummaryDtoFiltersLinkStatus =
  (typeof AdminTestAnalyticsSummaryDtoFiltersLinkStatus)[keyof typeof AdminTestAnalyticsSummaryDtoFiltersLinkStatus];

export const AdminTestAnalyticsSummaryDtoFiltersLinkStatus = {
  ALL: 'ALL',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
} as const;
