/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminPublicAttemptDetailResponseDtoEntryProfileMode =
  (typeof AdminPublicAttemptDetailResponseDtoEntryProfileMode)[keyof typeof AdminPublicAttemptDetailResponseDtoEntryProfileMode];

export const AdminPublicAttemptDetailResponseDtoEntryProfileMode = {
  DEMOGRAPHIC: 'DEMOGRAPHIC',
  EDUCATION: 'EDUCATION',
  EDUCATION_DEMOGRAPHIC: 'EDUCATION_DEMOGRAPHIC',
} as const;
