/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AdminUserCredentialsResponseDtoUserRole =
  (typeof AdminUserCredentialsResponseDtoUserRole)[keyof typeof AdminUserCredentialsResponseDtoUserRole];

export const AdminUserCredentialsResponseDtoUserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
