/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AnalysisPromptListResponseDtoPromptsItemVersionsItemStatus =
  (typeof AnalysisPromptListResponseDtoPromptsItemVersionsItemStatus)[keyof typeof AnalysisPromptListResponseDtoPromptsItemVersionsItemStatus];

export const AnalysisPromptListResponseDtoPromptsItemVersionsItemStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;
