/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AnalysisPromptResponseDtoPromptVersionsItemStatus =
  (typeof AnalysisPromptResponseDtoPromptVersionsItemStatus)[keyof typeof AnalysisPromptResponseDtoPromptVersionsItemStatus];

export const AnalysisPromptResponseDtoPromptVersionsItemStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;
