/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AnalysisPromptVersionResponseDtoVersion } from './analysisPromptVersionResponseDtoVersion';

export interface AnalysisPromptVersionResponseDto {
  version: AnalysisPromptVersionResponseDtoVersion;
}
