/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AnalysisPromptResponseDtoPrompt } from './analysisPromptResponseDtoPrompt';

export interface AnalysisPromptResponseDto {
  prompt: AnalysisPromptResponseDtoPrompt;
}
