/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AnalysisPromptVersionResponseDtoVersionStatus = typeof AnalysisPromptVersionResponseDtoVersionStatus[keyof typeof AnalysisPromptVersionResponseDtoVersionStatus];


export const AnalysisPromptVersionResponseDtoVersionStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;
