/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AnalysisPromptResponseDtoPromptActiveTestsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  topicId: number;
  title: string;
  slug: string;
  onPublishedVersion: boolean;
};
