/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { AuditHistoryResponseDtoEventsItemActor } from './auditHistoryResponseDtoEventsItemActor';
import type { AuditHistoryResponseDtoEventsItemChangesItem } from './auditHistoryResponseDtoEventsItemChangesItem';

export type AuditHistoryResponseDtoEventsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  action: string;
  /** @nullable */
  actor: AuditHistoryResponseDtoEventsItemActor;
  changes: AuditHistoryResponseDtoEventsItemChangesItem[];
  createdAt: string;
};
