/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type AuthResponseDtoUserRole =
  (typeof AuthResponseDtoUserRole)[keyof typeof AuthResponseDtoUserRole];

export const AuthResponseDtoUserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
