/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { CreateTestsTopicFromAiDtoQuestionsItemOptionsItem } from './createTestsTopicFromAiDtoQuestionsItemOptionsItem';
import type { CreateTestsTopicFromAiDtoQuestionsItemSettings } from './createTestsTopicFromAiDtoQuestionsItemSettings';
import type { CreateTestsTopicFromAiDtoQuestionsItemSliderBandsItem } from './createTestsTopicFromAiDtoQuestionsItemSliderBandsItem';
import type { CreateTestsTopicFromAiDtoQuestionsItemType } from './createTestsTopicFromAiDtoQuestionsItemType';

export type CreateTestsTopicFromAiDtoQuestionsItem = {
  type: CreateTestsTopicFromAiDtoQuestionsItemType;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  required?: boolean;
  settings?: CreateTestsTopicFromAiDtoQuestionsItemSettings;
  options?: CreateTestsTopicFromAiDtoQuestionsItemOptionsItem[];
  sliderBands?: CreateTestsTopicFromAiDtoQuestionsItemSliderBandsItem[];
};
