/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface CreateCalculationDto {
  /** The mathematical expression (e.g. "2 + 2") */
  expression: string;
  /** The calculated result */
  result: string;
}
