/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { CreateTestsTopicFromAiDtoQuestionsItem } from './createTestsTopicFromAiDtoQuestionsItem';

export interface CreateTestsTopicFromAiDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  slug?: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  /**
   * @minItems 1
   * @maxItems 60
   */
  questions: CreateTestsTopicFromAiDtoQuestionsItem[];
}
