/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface CreateNoteDto {
  /**
   * The note title
   * @minLength 1
   */
  title: string;
  /** The note content */
  content: string;
}
