/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type CreateTestsTopicFromAiDtoQuestionsItemOptionsItem = {
  /**
   * @minLength 1
   * @maxLength 400
   */
  label: string;
  /**
   * @minLength 1
   * @maxLength 400
   */
  value: string;
  /**
   * @minimum -1000
   * @maximum 1000
   */
  weight?: number;
};
