/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email?: string;
  /** @minLength 2 */
  name?: string;
  role?: CreateUserDtoRole;
  /** @minLength 8 */
  password?: string;
}
