/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface CreateTestsTopicDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  slug?: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
}
