/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type ErrorResponseDtoError = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  statusCode: number;
  code: string;
  message: string;
  details: unknown[];
};
