/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type GeneratePromptDtoResponseFormat =
  (typeof GeneratePromptDtoResponseFormat)[keyof typeof GeneratePromptDtoResponseFormat];

export const GeneratePromptDtoResponseFormat = {
  text: 'text',
  json: 'json',
} as const;
