/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { GeneratePromptDtoResponseFormat } from './generatePromptDtoResponseFormat';

export interface GeneratePromptDto {
  /** @minLength 1 */
  model: string;
  /**
   * @minLength 1
   * @maxLength 8000
   */
  prompt: string;
  /**
   * @minimum 0
   * @maximum 2
   */
  temperature?: number;
  responseFormat?: GeneratePromptDtoResponseFormat;
}
