/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { ProfessionAtlasCoverageResponseDtoItemsItemMatchesItem } from './professionAtlasCoverageResponseDtoItemsItemMatchesItem';
import type { ProfessionAtlasCoverageResponseDtoItemsItemStatus } from './professionAtlasCoverageResponseDtoItemsItemStatus';

export type ProfessionAtlasCoverageResponseDtoItemsItem = {
  title: string;
  status: ProfessionAtlasCoverageResponseDtoItemsItemStatus;
  matches: ProfessionAtlasCoverageResponseDtoItemsItemMatchesItem[];
};
