/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type ProfessionAtlasCoverageResponseDtoItemsItemStatus =
  (typeof ProfessionAtlasCoverageResponseDtoItemsItemStatus)[keyof typeof ProfessionAtlasCoverageResponseDtoItemsItemStatus];

export const ProfessionAtlasCoverageResponseDtoItemsItemStatus = {
  found: 'found',
  missing: 'missing',
  duplicate: 'duplicate',
} as const;
