/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type ProfessionAtlasCoverageResponseDtoStatus =
  (typeof ProfessionAtlasCoverageResponseDtoStatus)[keyof typeof ProfessionAtlasCoverageResponseDtoStatus];

export const ProfessionAtlasCoverageResponseDtoStatus = {
  ready: 'ready',
  partial: 'partial',
  unavailable: 'unavailable',
} as const;
