/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface ProjectResponseDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  title: string;
  /** @nullable */
  description: string | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  userId: number;
  createdAt: string;
  updatedAt: string;
}
