/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PromptTestQuestionsResponseDtoTestsItemQuestionsItem } from './promptTestQuestionsResponseDtoTestsItemQuestionsItem';

export type PromptTestQuestionsResponseDtoTestsItem = {
  id: number;
  topicId: number;
  topicSlug: string;
  title: string;
  /** @nullable */
  description: string | null;
  versionNumber: number;
  versionStatus: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  questionCount: number;
  questions: PromptTestQuestionsResponseDtoTestsItemQuestionsItem[];
};
