/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface PromptSimulationResponseDto {
  model: string;
  output: string;
  syntheticAnswers: unknown | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  questionCount: number;
}
