/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PromptTestQuestionsResponseDtoTestsItem } from './promptTestQuestionsResponseDtoTestsItem';

export interface PromptTestQuestionsResponseDto {
  tests: PromptTestQuestionsResponseDtoTestsItem[];
}
