/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface PromptSimulationRequestDto {
  /**
   * @minLength 1
   * @maxLength 12000
   */
  prompt: string;
  /** @minLength 1 */
  model: string;
  /**
   * @minimum 0
   * @maximum 2
   */
  temperature?: number;
  /**
   * @minItems 1
   * @items.minimum 1
   * @items.maximum 9007199254740991
   */
  questionIds: number[];
  generateAnswers?: boolean;
}
