/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface PublicSessionStartRequestDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  studentName: string;
  /**
   * @minLength 1
   * @maxLength 1
   */
  studentLastInitial: string;
  /**
   * @minLength 1
   * @maxLength 1
   */
  studentMiddleInitial: string;
  /**
   * @minLength 1
   * @maxLength 300
   */
  educationOrganization: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  groupOrClass: string;
  consentAccepted: boolean;
}
