/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicLinkAccessResponseDtoGroupValidationMode =
  (typeof PublicLinkAccessResponseDtoGroupValidationMode)[keyof typeof PublicLinkAccessResponseDtoGroupValidationMode];

export const PublicLinkAccessResponseDtoGroupValidationMode = {
  NONE: 'NONE',
  HINT: 'HINT',
  STRICT: 'STRICT',
} as const;
