/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionResultResponseDtoAnalysis } from './publicSessionResultResponseDtoAnalysis';
import type { PublicSessionResultResponseDtoStatus } from './publicSessionResultResponseDtoStatus';

export interface PublicSessionResultResponseDto {
  sessionToken: string;
  status: PublicSessionResultResponseDtoStatus;
  /** @nullable */
  finishedAt: string | null;
  analysis: PublicSessionResultResponseDtoAnalysis;
}
