/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionStartResponseDtoSessionAnswersItem } from './publicSessionStartResponseDtoSessionAnswersItem';
import type { PublicSessionStartResponseDtoSessionPublicBranding } from './publicSessionStartResponseDtoSessionPublicBranding';
import type { PublicSessionStartResponseDtoSessionPublicTemplate } from './publicSessionStartResponseDtoSessionPublicTemplate';
import type { PublicSessionStartResponseDtoSessionQuestionsItem } from './publicSessionStartResponseDtoSessionQuestionsItem';
import type { PublicSessionStartResponseDtoSessionStatus } from './publicSessionStartResponseDtoSessionStatus';

export type PublicSessionStartResponseDtoSession = {
  sessionToken: string;
  shortCode: string;
  publicTemplate: PublicSessionStartResponseDtoSessionPublicTemplate;
  /** @nullable */
  publicBranding: PublicSessionStartResponseDtoSessionPublicBranding;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptNumber: number;
  status: PublicSessionStartResponseDtoSessionStatus;
  startedAt: string;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  finishedAt: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  timeLimitMinutes: number | null;
  questions: PublicSessionStartResponseDtoSessionQuestionsItem[];
  answers: PublicSessionStartResponseDtoSessionAnswersItem[];
};
