/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionStartResponseDtoSessionPublicBrandingAccents } from './publicSessionStartResponseDtoSessionPublicBrandingAccents';
import type { PublicSessionStartResponseDtoSessionPublicBrandingBackground } from './publicSessionStartResponseDtoSessionPublicBrandingBackground';
import type { PublicSessionStartResponseDtoSessionPublicBrandingButtons } from './publicSessionStartResponseDtoSessionPublicBrandingButtons';
import type { PublicSessionStartResponseDtoSessionPublicBrandingHeader } from './publicSessionStartResponseDtoSessionPublicBrandingHeader';
import type { PublicSessionStartResponseDtoSessionPublicBrandingSurfaces } from './publicSessionStartResponseDtoSessionPublicBrandingSurfaces';
import type { PublicSessionStartResponseDtoSessionPublicBrandingVersion } from './publicSessionStartResponseDtoSessionPublicBrandingVersion';

/**
 * @nullable
 */
export type PublicSessionStartResponseDtoSessionPublicBranding = {
  version: PublicSessionStartResponseDtoSessionPublicBrandingVersion;
  background?: PublicSessionStartResponseDtoSessionPublicBrandingBackground;
  header?: PublicSessionStartResponseDtoSessionPublicBrandingHeader;
  buttons?: PublicSessionStartResponseDtoSessionPublicBrandingButtons;
  surfaces?: PublicSessionStartResponseDtoSessionPublicBrandingSurfaces;
  accents?: PublicSessionStartResponseDtoSessionPublicBrandingAccents;
} | null;
