/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionResultResponseDtoAnalysisStatus = typeof PublicSessionResultResponseDtoAnalysisStatus[keyof typeof PublicSessionResultResponseDtoAnalysisStatus];


export const PublicSessionResultResponseDtoAnalysisStatus = {
  PENDING: 'PENDING',
  READY: 'READY',
  FAILED: 'FAILED',
} as const;
