/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionGetResponseDtoSessionPublicBrandingAccents } from './publicSessionGetResponseDtoSessionPublicBrandingAccents';
import type { PublicSessionGetResponseDtoSessionPublicBrandingBackground } from './publicSessionGetResponseDtoSessionPublicBrandingBackground';
import type { PublicSessionGetResponseDtoSessionPublicBrandingButtons } from './publicSessionGetResponseDtoSessionPublicBrandingButtons';
import type { PublicSessionGetResponseDtoSessionPublicBrandingHeader } from './publicSessionGetResponseDtoSessionPublicBrandingHeader';
import type { PublicSessionGetResponseDtoSessionPublicBrandingSurfaces } from './publicSessionGetResponseDtoSessionPublicBrandingSurfaces';
import type { PublicSessionGetResponseDtoSessionPublicBrandingVersion } from './publicSessionGetResponseDtoSessionPublicBrandingVersion';

/**
 * @nullable
 */
export type PublicSessionGetResponseDtoSessionPublicBranding = {
  version: PublicSessionGetResponseDtoSessionPublicBrandingVersion;
  background?: PublicSessionGetResponseDtoSessionPublicBrandingBackground;
  header?: PublicSessionGetResponseDtoSessionPublicBrandingHeader;
  buttons?: PublicSessionGetResponseDtoSessionPublicBrandingButtons;
  surfaces?: PublicSessionGetResponseDtoSessionPublicBrandingSurfaces;
  accents?: PublicSessionGetResponseDtoSessionPublicBrandingAccents;
} | null;
