/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionFinishResponseDtoAnalysisProviderMode } from './publicSessionFinishResponseDtoAnalysisProviderMode';
import type { PublicSessionFinishResponseDtoAnalysisStatus } from './publicSessionFinishResponseDtoAnalysisStatus';

export type PublicSessionFinishResponseDtoAnalysis = {
  providerMode: PublicSessionFinishResponseDtoAnalysisProviderMode;
  status: PublicSessionFinishResponseDtoAnalysisStatus;
  summary: unknown | null;
  /** @nullable */
  rawText: string | null;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  generatedAt: string | null;
};
