/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionStartRequestDtoGender =
  (typeof PublicSessionStartRequestDtoGender)[keyof typeof PublicSessionStartRequestDtoGender];

export const PublicSessionStartRequestDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
