/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicLinkAccessResponseDtoPersonalDataProcessingMode } from './publicLinkAccessResponseDtoPersonalDataProcessingMode';

export type PublicLinkAccessResponseDtoPersonalData = {
  processingMode: PublicLinkAccessResponseDtoPersonalDataProcessingMode;
  operatorFullName: string;
  /** @nullable */
  operatorShortName: string | null;
  privacyPolicyUrl: string;
  /** @nullable */
  consentDocumentUrl: string | null;
  /** @nullable */
  logoUrl: string | null;
};
