/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface PublicLinkAccessResponseDto {
  shortCode: string;
  title: string;
  /** @nullable */
  description: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  questionCount: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  maxAttemptsPerStudent: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  timeLimitMinutes: number | null;
  allowResume: boolean;
  /** @nullable */
  startsAt: string | null;
  /** @nullable */
  endsAt: string | null;
  consentVersion: string;
  consentText: string;
}
