/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionResultResponseDtoAnalysisProviderMode } from './publicSessionResultResponseDtoAnalysisProviderMode';
import type { PublicSessionResultResponseDtoAnalysisStatus } from './publicSessionResultResponseDtoAnalysisStatus';
import type { PublicSessionResultResponseDtoAnalysisSummary } from './publicSessionResultResponseDtoAnalysisSummary';

export type PublicSessionResultResponseDtoAnalysis = {
  providerMode: PublicSessionResultResponseDtoAnalysisProviderMode;
  status: PublicSessionResultResponseDtoAnalysisStatus;
  /** @nullable */
  summary: PublicSessionResultResponseDtoAnalysisSummary;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  generatedAt: string | null;
};
