/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionStartResponseDtoSessionPublicBrandingVersion =
  (typeof PublicSessionStartResponseDtoSessionPublicBrandingVersion)[keyof typeof PublicSessionStartResponseDtoSessionPublicBrandingVersion];

export const PublicSessionStartResponseDtoSessionPublicBrandingVersion = {
  NUMBER_1: 1,
} as const;
