/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionResultResponseDtoAnalysisProviderMode } from './publicSessionResultResponseDtoAnalysisProviderMode';
import type { PublicSessionResultResponseDtoAnalysisStatus } from './publicSessionResultResponseDtoAnalysisStatus';

export type PublicSessionResultResponseDtoAnalysis = {
  providerMode: PublicSessionResultResponseDtoAnalysisProviderMode;
  status: PublicSessionResultResponseDtoAnalysisStatus;
  summary: unknown | null;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  generatedAt: string | null;
};
