/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionStartRequestDtoEntryProfileMode =
  (typeof PublicSessionStartRequestDtoEntryProfileMode)[keyof typeof PublicSessionStartRequestDtoEntryProfileMode];

export const PublicSessionStartRequestDtoEntryProfileMode = {
  DEMOGRAPHIC: 'DEMOGRAPHIC',
  EDUCATION: 'EDUCATION',
} as const;
