/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionFinishResponseDtoAnalysisProviderMode } from './publicSessionFinishResponseDtoAnalysisProviderMode';
import type { PublicSessionFinishResponseDtoAnalysisStatus } from './publicSessionFinishResponseDtoAnalysisStatus';
import type { PublicSessionFinishResponseDtoAnalysisSummary } from './publicSessionFinishResponseDtoAnalysisSummary';

export type PublicSessionFinishResponseDtoAnalysis = {
  providerMode: PublicSessionFinishResponseDtoAnalysisProviderMode;
  status: PublicSessionFinishResponseDtoAnalysisStatus;
  /** @nullable */
  summary: PublicSessionFinishResponseDtoAnalysisSummary;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  generatedAt: string | null;
};
