/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionStartResponseDtoSessionQuestionsItemOptionsItem } from './publicSessionStartResponseDtoSessionQuestionsItemOptionsItem';
import type { PublicSessionStartResponseDtoSessionQuestionsItemSliderBandsItem } from './publicSessionStartResponseDtoSessionQuestionsItemSliderBandsItem';
import type { PublicSessionStartResponseDtoSessionQuestionsItemType } from './publicSessionStartResponseDtoSessionQuestionsItemType';

export type PublicSessionStartResponseDtoSessionQuestionsItem = {
  id: number;
  type: PublicSessionStartResponseDtoSessionQuestionsItemType;
  title: string;
  /** @nullable */
  description: string | null;
  required: boolean;
  order: number;
  settings: unknown | null;
  options: PublicSessionStartResponseDtoSessionQuestionsItemOptionsItem[];
  sliderBands: PublicSessionStartResponseDtoSessionQuestionsItemSliderBandsItem[];
};
