/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicLinkAccessResponseDtoPublicTemplate =
  (typeof PublicLinkAccessResponseDtoPublicTemplate)[keyof typeof PublicLinkAccessResponseDtoPublicTemplate];

export const PublicLinkAccessResponseDtoPublicTemplate = {
  STANDARD: 'STANDARD',
  POLUS: 'POLUS',
} as const;
