/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type PublicSessionFinishResponseDtoAnalysisSummary = { [key: string]: unknown } | null;
