/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionGetResponseDtoSessionStatus =
  (typeof PublicSessionGetResponseDtoSessionStatus)[keyof typeof PublicSessionGetResponseDtoSessionStatus];

export const PublicSessionGetResponseDtoSessionStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  ABANDONED: 'ABANDONED',
} as const;
