/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionResultResponseDtoAnalysisProviderMode =
  (typeof PublicSessionResultResponseDtoAnalysisProviderMode)[keyof typeof PublicSessionResultResponseDtoAnalysisProviderMode];

export const PublicSessionResultResponseDtoAnalysisProviderMode = {
  STUB: 'STUB',
  LLM: 'LLM',
} as const;
