/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItemSize =
  (typeof PublicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItemSize)[keyof typeof PublicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItemSize];

export const PublicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItemSize = {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
