/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionSaveAnswersResponseDtoAnswersItem = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  questionId: number;
  answerPayload: string | string[] | number;
  updatedAt: string;
};
