/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionGetResponseDtoSessionPublicTemplate =
  (typeof PublicSessionGetResponseDtoSessionPublicTemplate)[keyof typeof PublicSessionGetResponseDtoSessionPublicTemplate];

export const PublicSessionGetResponseDtoSessionPublicTemplate = {
  STANDARD: 'STANDARD',
  POLUS: 'POLUS',
} as const;
