/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * Статус алгоритмической записи анализа (не является признаком завершения LLM-обогащения)
 */
export type PublicSessionFinishResponseDtoAnalysisStatus =
  (typeof PublicSessionFinishResponseDtoAnalysisStatus)[keyof typeof PublicSessionFinishResponseDtoAnalysisStatus];

export const PublicSessionFinishResponseDtoAnalysisStatus = {
  PENDING: 'PENDING',
  READY: 'READY',
  FAILED: 'FAILED',
} as const;
