/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionGetResponseDtoSessionQuestionsItemType =
  (typeof PublicSessionGetResponseDtoSessionQuestionsItemType)[keyof typeof PublicSessionGetResponseDtoSessionQuestionsItemType];

export const PublicSessionGetResponseDtoSessionQuestionsItemType = {
  OPEN_TEXT: 'OPEN_TEXT',
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTI_CHOICE: 'MULTI_CHOICE',
  SLIDER: 'SLIDER',
} as const;
