/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicLinkAccessResponseDtoPublicBrandingAccents } from './publicLinkAccessResponseDtoPublicBrandingAccents';
import type { PublicLinkAccessResponseDtoPublicBrandingBackground } from './publicLinkAccessResponseDtoPublicBrandingBackground';
import type { PublicLinkAccessResponseDtoPublicBrandingButtons } from './publicLinkAccessResponseDtoPublicBrandingButtons';
import type { PublicLinkAccessResponseDtoPublicBrandingHeader } from './publicLinkAccessResponseDtoPublicBrandingHeader';
import type { PublicLinkAccessResponseDtoPublicBrandingSurfaces } from './publicLinkAccessResponseDtoPublicBrandingSurfaces';
import type { PublicLinkAccessResponseDtoPublicBrandingVersion } from './publicLinkAccessResponseDtoPublicBrandingVersion';

/**
 * @nullable
 */
export type PublicLinkAccessResponseDtoPublicBranding = {
  version: PublicLinkAccessResponseDtoPublicBrandingVersion;
  background?: PublicLinkAccessResponseDtoPublicBrandingBackground;
  header?: PublicLinkAccessResponseDtoPublicBrandingHeader;
  buttons?: PublicLinkAccessResponseDtoPublicBrandingButtons;
  surfaces?: PublicLinkAccessResponseDtoPublicBrandingSurfaces;
  accents?: PublicLinkAccessResponseDtoPublicBrandingAccents;
} | null;
