/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicLinkAccessResponseDtoPublicBrandingVersion =
  (typeof PublicLinkAccessResponseDtoPublicBrandingVersion)[keyof typeof PublicLinkAccessResponseDtoPublicBrandingVersion];

export const PublicLinkAccessResponseDtoPublicBrandingVersion = {
  NUMBER_1: 1,
} as const;
