/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionResultResponseDtoPublicBrandingAccents } from './publicSessionResultResponseDtoPublicBrandingAccents';
import type { PublicSessionResultResponseDtoPublicBrandingBackground } from './publicSessionResultResponseDtoPublicBrandingBackground';
import type { PublicSessionResultResponseDtoPublicBrandingButtons } from './publicSessionResultResponseDtoPublicBrandingButtons';
import type { PublicSessionResultResponseDtoPublicBrandingHeader } from './publicSessionResultResponseDtoPublicBrandingHeader';
import type { PublicSessionResultResponseDtoPublicBrandingSurfaces } from './publicSessionResultResponseDtoPublicBrandingSurfaces';
import type { PublicSessionResultResponseDtoPublicBrandingVersion } from './publicSessionResultResponseDtoPublicBrandingVersion';

/**
 * @nullable
 */
export type PublicSessionResultResponseDtoPublicBranding = {
  version: PublicSessionResultResponseDtoPublicBrandingVersion;
  background?: PublicSessionResultResponseDtoPublicBrandingBackground;
  header?: PublicSessionResultResponseDtoPublicBrandingHeader;
  buttons?: PublicSessionResultResponseDtoPublicBrandingButtons;
  surfaces?: PublicSessionResultResponseDtoPublicBrandingSurfaces;
  accents?: PublicSessionResultResponseDtoPublicBrandingAccents;
} | null;
