/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicLinkAccessResponseDtoPersonalDataProcessingMode =
  (typeof PublicLinkAccessResponseDtoPersonalDataProcessingMode)[keyof typeof PublicLinkAccessResponseDtoPersonalDataProcessingMode];

export const PublicLinkAccessResponseDtoPersonalDataProcessingMode = {
  PUBLIC: 'PUBLIC',
  ON_BEHALF_OF_EDUCATION_ORGANIZATION: 'ON_BEHALF_OF_EDUCATION_ORGANIZATION',
} as const;
