/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionGetResponseDtoSessionAnswersItem } from './publicSessionGetResponseDtoSessionAnswersItem';
import type { PublicSessionGetResponseDtoSessionPublicBranding } from './publicSessionGetResponseDtoSessionPublicBranding';
import type { PublicSessionGetResponseDtoSessionPublicTemplate } from './publicSessionGetResponseDtoSessionPublicTemplate';
import type { PublicSessionGetResponseDtoSessionQuestionsItem } from './publicSessionGetResponseDtoSessionQuestionsItem';
import type { PublicSessionGetResponseDtoSessionStatus } from './publicSessionGetResponseDtoSessionStatus';

export type PublicSessionGetResponseDtoSession = {
  sessionToken: string;
  shortCode: string;
  publicTemplate: PublicSessionGetResponseDtoSessionPublicTemplate;
  /** @nullable */
  publicBranding: PublicSessionGetResponseDtoSessionPublicBranding;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  attemptNumber: number;
  status: PublicSessionGetResponseDtoSessionStatus;
  startedAt: string;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  finishedAt: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  timeLimitMinutes: number | null;
  questions: PublicSessionGetResponseDtoSessionQuestionsItem[];
  answers: PublicSessionGetResponseDtoSessionAnswersItem[];
};
