/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicLinkAccessResponseDtoEntryProfileMode } from './publicLinkAccessResponseDtoEntryProfileMode';
import type { PublicLinkAccessResponseDtoGroupValidationMode } from './publicLinkAccessResponseDtoGroupValidationMode';
import type { PublicLinkAccessResponseDtoPersonalData } from './publicLinkAccessResponseDtoPersonalData';
import type { PublicLinkAccessResponseDtoPublicBranding } from './publicLinkAccessResponseDtoPublicBranding';
import type { PublicLinkAccessResponseDtoPublicTemplate } from './publicLinkAccessResponseDtoPublicTemplate';

export interface PublicLinkAccessResponseDto {
  shortCode: string;
  title: string;
  /** @nullable */
  description: string | null;
  entryProfileMode: PublicLinkAccessResponseDtoEntryProfileMode;
  publicTemplate: PublicLinkAccessResponseDtoPublicTemplate;
  /** @nullable */
  publicBranding: PublicLinkAccessResponseDtoPublicBranding;
  /** @nullable */
  educationOrganization: string | null;
  groupValidationMode: PublicLinkAccessResponseDtoGroupValidationMode;
  /** @nullable */
  groupValidationPattern: string | null;
  /** @nullable */
  groupValidationExample: string | null;
  /** @nullable */
  groupValidationHint: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  questionCount: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  maxAttemptsPerStudent: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  timeLimitMinutes: number | null;
  allowResume: boolean;
  /** @nullable */
  startsAt: string | null;
  /** @nullable */
  endsAt: string | null;
  consentVersion: string;
  consentText: string;
  personalData: PublicLinkAccessResponseDtoPersonalData;
}
