/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionResultResponseDtoPublicBrandingBackgroundMode =
  (typeof PublicSessionResultResponseDtoPublicBrandingBackgroundMode)[keyof typeof PublicSessionResultResponseDtoPublicBrandingBackgroundMode];

export const PublicSessionResultResponseDtoPublicBrandingBackgroundMode = {
  default: 'default',
  solid: 'solid',
  image: 'image',
} as const;
