/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionResultResponseDtoPublicBrandingVersion =
  (typeof PublicSessionResultResponseDtoPublicBrandingVersion)[keyof typeof PublicSessionResultResponseDtoPublicBrandingVersion];

export const PublicSessionResultResponseDtoPublicBrandingVersion = {
  NUMBER_1: 1,
} as const;
