/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionResultResponseDtoPublicBrandingHeaderLogosItem } from './publicSessionResultResponseDtoPublicBrandingHeaderLogosItem';

export type PublicSessionResultResponseDtoPublicBrandingHeader = {
  /** @maxItems 2 */
  logos?: PublicSessionResultResponseDtoPublicBrandingHeaderLogosItem[];
};
