/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type PublicLinkAccessResponseDtoPublicBranding = {
  version: 1;
  background?: {
    mode?: 'default' | 'solid' | 'image';
    /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
    color?: string;
    /** @maxLength 2048 */
    imageUrl?: string;
    /**
     * @minimum 0
     * @maximum 0.85
     */
    overlay?: number;
  };
  header?: {
    /** @maxItems 2 */
    logos?: {
      /** @maxLength 2048 */
      url: string;
      /**
       * @minLength 1
       * @maxLength 120
       */
      alt: string;
      size?: 'sm' | 'md' | 'lg';
    }[];
  };
  buttons?: {
    /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
    primaryColor?: string;
    /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
    textColor?: string;
  };
  surfaces?: {
    /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
    cardColor?: string;
    /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
    borderColor?: string;
  };
  accents?: {
    /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
    accentColor?: string;
  };
} | null;
