/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionGetResponseDtoSessionQuestionsItemOptionsItem } from './publicSessionGetResponseDtoSessionQuestionsItemOptionsItem';
import type { PublicSessionGetResponseDtoSessionQuestionsItemSliderBandsItem } from './publicSessionGetResponseDtoSessionQuestionsItemSliderBandsItem';
import type { PublicSessionGetResponseDtoSessionQuestionsItemType } from './publicSessionGetResponseDtoSessionQuestionsItemType';

export type PublicSessionGetResponseDtoSessionQuestionsItem = {
  id: number;
  type: PublicSessionGetResponseDtoSessionQuestionsItemType;
  title: string;
  /** @nullable */
  description: string | null;
  required: boolean;
  order: number;
  settings: unknown | null;
  options: PublicSessionGetResponseDtoSessionQuestionsItemOptionsItem[];
  sliderBands: PublicSessionGetResponseDtoSessionQuestionsItemSliderBandsItem[];
};
