/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionResultResponseDtoPublicBrandingHeaderLogosItemSize =
  (typeof PublicSessionResultResponseDtoPublicBrandingHeaderLogosItemSize)[keyof typeof PublicSessionResultResponseDtoPublicBrandingHeaderLogosItemSize];

export const PublicSessionResultResponseDtoPublicBrandingHeaderLogosItemSize = {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
