/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionSaveAnswersResponseDtoStatus = typeof PublicSessionSaveAnswersResponseDtoStatus[keyof typeof PublicSessionSaveAnswersResponseDtoStatus];


export const PublicSessionSaveAnswersResponseDtoStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  ABANDONED: 'ABANDONED',
} as const;
