/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicLinkAccessResponseDtoPublicBrandingHeaderLogosItemSize =
  (typeof PublicLinkAccessResponseDtoPublicBrandingHeaderLogosItemSize)[keyof typeof PublicLinkAccessResponseDtoPublicBrandingHeaderLogosItemSize];

export const PublicLinkAccessResponseDtoPublicBrandingHeaderLogosItemSize = {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
