/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionGetResponseDtoSessionPublicBrandingBackgroundMode =
  (typeof PublicSessionGetResponseDtoSessionPublicBrandingBackgroundMode)[keyof typeof PublicSessionGetResponseDtoSessionPublicBrandingBackgroundMode];

export const PublicSessionGetResponseDtoSessionPublicBrandingBackgroundMode = {
  default: 'default',
  solid: 'solid',
  image: 'image',
} as const;
