/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { PublicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItem } from './publicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItem';

export type PublicSessionStartResponseDtoSessionPublicBrandingHeader = {
  /** @maxItems 2 */
  logos?: PublicSessionStartResponseDtoSessionPublicBrandingHeaderLogosItem[];
};
