/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionGetResponseDtoSessionQuestionsItemOptionsItem = {
  id: number;
  label: string;
  value: string;
  order: number;
};
