/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionStartResponseDtoSessionPublicBrandingBackgroundMode =
  (typeof PublicSessionStartResponseDtoSessionPublicBrandingBackgroundMode)[keyof typeof PublicSessionStartResponseDtoSessionPublicBrandingBackgroundMode];

export const PublicSessionStartResponseDtoSessionPublicBrandingBackgroundMode = {
  default: 'default',
  solid: 'solid',
  image: 'image',
} as const;
