/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type PublicSessionFinishResponseDtoAnalysisProviderMode =
  (typeof PublicSessionFinishResponseDtoAnalysisProviderMode)[keyof typeof PublicSessionFinishResponseDtoAnalysisProviderMode];

export const PublicSessionFinishResponseDtoAnalysisProviderMode = {
  STUB: 'STUB',
  LLM: 'LLM',
} as const;
