/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface TaskResponseDto {
  id: number;
  title: string;
  done: boolean;
  userId: number;
  /** ISO Date string */
  createdAt: string;
  /** ISO Date string */
  updatedAt: string;
}
