/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { TestsTopicDetailResponseDtoDraft } from './testsTopicDetailResponseDtoDraft';
import type { TestsTopicDetailResponseDtoPublished } from './testsTopicDetailResponseDtoPublished';

export interface TestsTopicDetailResponseDto {
  topicId: number;
  slug: string;
  draft: TestsTopicDetailResponseDtoDraft;
  /** @nullable */
  published: TestsTopicDetailResponseDtoPublished;
}
