/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type TestsTopicListResponseDtoTopicsItem = {
  id: number;
  slug: string;
  draftVersionNumber: number;
  draftTitle: string;
  draftQuestionCount: number;
  /** @nullable */
  publishedVersionNumber: number | null;
  /** @nullable */
  publishedTitle: string | null;
  updatedAt: string;
};
