/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { TestsTopicDetailResponseDtoDraftAnalysisPromptVersion } from './testsTopicDetailResponseDtoDraftAnalysisPromptVersion';
import type { TestsTopicDetailResponseDtoDraftQuestionsItem } from './testsTopicDetailResponseDtoDraftQuestionsItem';

export type TestsTopicDetailResponseDtoDraft = {
  id: number;
  versionNumber: number;
  title: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  analysisPromptVersion: TestsTopicDetailResponseDtoDraftAnalysisPromptVersion;
  questions: TestsTopicDetailResponseDtoDraftQuestionsItem[];
};
