/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type TestsAdminAnalyticsControllerExportPdfScope =
  (typeof TestsAdminAnalyticsControllerExportPdfScope)[keyof typeof TestsAdminAnalyticsControllerExportPdfScope];

export const TestsAdminAnalyticsControllerExportPdfScope = {
  TOPIC: 'TOPIC',
  PUBLIC_LINK: 'PUBLIC_LINK',
} as const;
