/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { TestsTopicListResponseDtoTopicsItemScoringKind } from './testsTopicListResponseDtoTopicsItemScoringKind';

export type TestsTopicListResponseDtoTopicsItem = {
  id: number;
  slug: string;
  /** @nullable */
  description: string | null;
  draftVersionNumber: number;
  draftTitle: string;
  draftQuestionCount: number;
  /** @nullable */
  publishedVersionNumber: number | null;
  /** @nullable */
  publishedTitle: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  activePublicLinkCount: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  attemptCount: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  publicLinkCount: number;
  hasPublishedVersion: boolean;
  canDelete: boolean;
  scoringKind: TestsTopicListResponseDtoTopicsItemScoringKind;
  hasUnpublishedChanges: boolean;
  updatedAt: string;
};
