/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { TestsAdminAnalyticsControllerExportXlsxLinkStatus } from './testsAdminAnalyticsControllerExportXlsxLinkStatus';
import type { TestsAdminAnalyticsControllerExportXlsxScope } from './testsAdminAnalyticsControllerExportXlsxScope';

export type TestsAdminAnalyticsControllerExportXlsxParams = {
  scope?: TestsAdminAnalyticsControllerExportXlsxScope;
  publicLinkId?: number;
  linkStatus?: TestsAdminAnalyticsControllerExportXlsxLinkStatus;
  dateFrom?: string;
  dateTo?: string;
};
