/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type TestsAdminAnalyticsControllerExportXlsxLinkStatus =
  (typeof TestsAdminAnalyticsControllerExportXlsxLinkStatus)[keyof typeof TestsAdminAnalyticsControllerExportXlsxLinkStatus];

export const TestsAdminAnalyticsControllerExportXlsxLinkStatus = {
  ALL: 'ALL',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
} as const;
