/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { TestsTopicDetailResponseDtoDraftQuestionsItemOptionsItem } from './testsTopicDetailResponseDtoDraftQuestionsItemOptionsItem';
import type { TestsTopicDetailResponseDtoDraftQuestionsItemSettings } from './testsTopicDetailResponseDtoDraftQuestionsItemSettings';
import type { TestsTopicDetailResponseDtoDraftQuestionsItemSliderBandsItem } from './testsTopicDetailResponseDtoDraftQuestionsItemSliderBandsItem';
import type { TestsTopicDetailResponseDtoDraftQuestionsItemType } from './testsTopicDetailResponseDtoDraftQuestionsItemType';

export type TestsTopicDetailResponseDtoDraftQuestionsItem = {
  id: number;
  type: TestsTopicDetailResponseDtoDraftQuestionsItemType;
  title: string;
  /** @nullable */
  description: string | null;
  required: boolean;
  order: number;
  /** @nullable */
  settings: TestsTopicDetailResponseDtoDraftQuestionsItemSettings;
  options: TestsTopicDetailResponseDtoDraftQuestionsItemOptionsItem[];
  sliderBands: TestsTopicDetailResponseDtoDraftQuestionsItemSliderBandsItem[];
};
