/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type TestsAdminAnalyticsControllerGetSummaryScope =
  (typeof TestsAdminAnalyticsControllerGetSummaryScope)[keyof typeof TestsAdminAnalyticsControllerGetSummaryScope];

export const TestsAdminAnalyticsControllerGetSummaryScope = {
  TOPIC: 'TOPIC',
  PUBLIC_LINK: 'PUBLIC_LINK',
} as const;
