/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type TestsAdminAnalyticsControllerExportXlsxScope =
  (typeof TestsAdminAnalyticsControllerExportXlsxScope)[keyof typeof TestsAdminAnalyticsControllerExportXlsxScope];

export const TestsAdminAnalyticsControllerExportXlsxScope = {
  TOPIC: 'TOPIC',
  PUBLIC_LINK: 'PUBLIC_LINK',
} as const;
