/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type TestsAdminAnalyticsControllerExportPdfLinkStatus =
  (typeof TestsAdminAnalyticsControllerExportPdfLinkStatus)[keyof typeof TestsAdminAnalyticsControllerExportPdfLinkStatus];

export const TestsAdminAnalyticsControllerExportPdfLinkStatus = {
  ALL: 'ALL',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
} as const;
