/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type TestsTopicDetailResponseDtoPublished = {
  id: number;
  versionNumber: number;
  title: string;
  /** @nullable */
  analysisPromptVersion: {
    id: number;
    promptId: number;
    promptTitle: string;
    versionNumber: number;
    model: string;
  } | null;
} | null;
