/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { TestsAdminAnalyticsControllerGetSummaryLinkStatus } from './testsAdminAnalyticsControllerGetSummaryLinkStatus';
import type { TestsAdminAnalyticsControllerGetSummaryScope } from './testsAdminAnalyticsControllerGetSummaryScope';

export type TestsAdminAnalyticsControllerGetSummaryParams = {
  scope?: TestsAdminAnalyticsControllerGetSummaryScope;
  publicLinkId?: number;
  linkStatus?: TestsAdminAnalyticsControllerGetSummaryLinkStatus;
  dateFrom?: string;
  dateTo?: string;
};
