/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { UpdateAiProviderDtoProvider } from './updateAiProviderDtoProvider';

export interface UpdateAiProviderDto {
  provider: UpdateAiProviderDtoProvider;
  /**
   * @maxLength 2048
   * @nullable
   */
  baseUrl: string | null;
  /**
   * @minLength 1
   * @maxLength 512
   */
  apiKey?: string;
  clearApiKey?: boolean;
  /**
   * @maxLength 256
   * @nullable
   */
  defaultModel: string | null;
}
