/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type UpdateAiProviderDtoProvider =
  (typeof UpdateAiProviderDtoProvider)[keyof typeof UpdateAiProviderDtoProvider];

export const UpdateAiProviderDtoProvider = {
  polza: 'polza',
  openrouter: 'openrouter',
  'openai-compatible': 'openai-compatible',
} as const;
