/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type UpdateUserStatusDtoStatus =
  (typeof UpdateUserStatusDtoStatus)[keyof typeof UpdateUserStatusDtoStatus];

export const UpdateUserStatusDtoStatus = {
  ACTIVE: 'ACTIVE',
  DEACTIVATED: 'DEACTIVATED',
} as const;
