/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface UpdateTestsTopicDraftDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  analysisPromptVersionId?: number | null;
}
