/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface UpdateAnalysisPromptVersionDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  /** @minLength 1 */
  model?: string;
  /**
   * @minimum 0
   * @maximum 2
   */
  temperature?: number;
  /**
   * @minLength 1
   * @maxLength 12000
   */
  prompt?: string;
}
