/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export interface UpdateProfessionAtlasUrlDto {
  /** @maxLength 2048 */
  publicUrl: string;
  /** @maxLength 2048 */
  apiUrl: string;
}
