/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */
import type { UpsertTestsQuestionDtoOptionsItem } from './upsertTestsQuestionDtoOptionsItem';
import type { UpsertTestsQuestionDtoSliderBandsItem } from './upsertTestsQuestionDtoSliderBandsItem';
import type { UpsertTestsQuestionDtoType } from './upsertTestsQuestionDtoType';

export interface UpsertTestsQuestionDto {
  type: UpsertTestsQuestionDtoType;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  required?: boolean;
  settings?: unknown;
  options?: UpsertTestsQuestionDtoOptionsItem[];
  sliderBands?: UpsertTestsQuestionDtoSliderBandsItem[];
}
