/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Fullstack Project API
 * The API documentation for our base project
 * OpenAPI spec version: 1.0
 */

export type UpsertTestsQuestionDtoSliderBandsItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  minValue: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  maxValue: number;
  /**
   * @minLength 1
   * @maxLength 400
   */
  label: string;
  /**
   * @minimum -1000
   * @maximum 1000
   */
  weight?: number;
};
