services:
  # База данных PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_app_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Веб-интерфейс для управления БД (http://localhost:8080)
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres_data:
