import {
  checkClientStorageDiscipline,
  checkDtoNoZodDate,
  isClientStorageException,
} from './invariant-rules.mjs';

/**
 * Top-level directories the guard knows how to reason about. An absolute path is trimmed down to
 * the first of these segments so the guard works the same whether the caller hands it a path
 * relative to the repo root or an absolute filesystem path (Windows or POSIX).
 */
const KNOWN_ROOTS = new Set([
  'client',
  'server',
  'scripts',
  'template',
  'docs',
  '.claude',
  '.husky',
]);

const toRepoRelative = (filePath) => {
  const posix = String(filePath).replace(/\\/g, '/');
  const segments = posix.split('/').filter(Boolean);
  const rootIndex = segments.findIndex((segment) => KNOWN_ROOTS.has(segment));
  if (rootIndex === -1) {
    return posix.replace(/^\/+/, '');
  }
  return segments.slice(rootIndex).join('/');
};

const GENERATED_API_PREFIXES = ['client/src/shared/api/generated/', 'client/src/shared/api/model/'];

const API_MUTATOR_PATH = 'client/src/shared/api/api.ts';
const API_MUTATOR_FORBIDDEN = /\b(window|localStorage|sessionStorage)\b|import\s*\.\s*meta/;

/**
 * Checks a pending Edit/Write for the four violations that account for most of the corrections
 * `npm run verify:invariants` catches after the fact. This is a best-effort, write-time hint, not
 * a replacement for the gate: it only sees the content being added, not the whole file, so it is
 * deliberately conservative and reuses the same detectors the gate uses wherever one exists.
 *
 * @param {{ toolName?: string, filePath: string, addedContent: string }} input
 * @returns {{ rule: string, message: string }[]}
 */
export const checkWriteGuard = ({ filePath, addedContent }) => {
  const violations = [];

  if (typeof filePath !== 'string' || filePath.length === 0) {
    return violations;
  }

  const relativePath = toRepoRelative(filePath);
  const source = typeof addedContent === 'string' ? addedContent : '';

  if (GENERATED_API_PREFIXES.some((prefix) => relativePath.startsWith(prefix))) {
    violations.push({
      rule: 'generated-api-client',
      message: `${relativePath} is generated by Orval and rewritten wholesale by "npm run gen:api"; edit the source contract (server DTOs/controllers) instead, not this generated output.`,
    });
  }

  if (relativePath === API_MUTATOR_PATH && API_MUTATOR_FORBIDDEN.test(source)) {
    violations.push({
      rule: 'inv-1-api-mutator',
      message:
        'client/src/shared/api/api.ts is imported by Orval in Node and must stay browser-free; move window/localStorage/sessionStorage/import.meta usage to client/src/shared/api/interceptors.ts.',
    });
  }

  if (
    relativePath.startsWith('client/src/') &&
    !isClientStorageException(relativePath) &&
    checkClientStorageDiscipline({ relativePath, source }).length > 0
  ) {
    violations.push({
      rule: 'inv-2-storage-discipline',
      message:
        'Direct use of localStorage/sessionStorage is forbidden; use safeStorage from @/shared/lib/storage instead.',
    });
  }

  if (
    relativePath.startsWith('server/src/') &&
    relativePath.endsWith('.ts') &&
    !relativePath.endsWith('.spec.ts') &&
    checkDtoNoZodDate({ relativePath, source }).length > 0
  ) {
    violations.push({
      rule: 'inv-4b-dto-no-zod-date',
      message:
        'z.date()/z.coerce.date() is forbidden in DTOs; response DTOs must convert dates to z.string() instead.',
    });
  }

  return violations;
};
